name: ResetAnvilRepairCost
version: '0.0.1'
main: me.duart.resetAnvilRepairCost.ResetAnvilRepairCost
description: | 
  Keeps the repair cost of an item in an anvil at a 
  lower level to prevent the TOO EXPENSIVE! text
api-version: '1.20'
