name: AnvilCost
version: '0.0.2'
main: me.duart.resetAnvilRepairCost.ResetAnvilRepairCost
description: | 
  Keeps the repair cost of an item in an anvil at a 
  lower level to prevent the TOO EXPENSIVE! text
api-version: '1.20'

commands:
  anvilresetcost:
    description: Reloads the plugin configuration
    permission: resetrepaircost.admin